# Generated by Django 2.1.1 on 2018-09-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('address', models.TextField(max_length=50)),
                ('mobile', models.TextField(max_length=13)),
                ('bld_group', models.TextField(max_length=2, verbose_name='Blood Group')),
                ('gender', models.CharField(max_length=2)),
            ],
        ),
    ]
