# Generated by Django 2.1.1 on 2018-09-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bld_group',
            field=models.CharField(max_length=2, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
    ]
