# Generated by Django 2.1.1 on 2018-09-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180926_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bld_group',
            field=models.CharField(max_length=3, verbose_name='Blood Group'),
        ),
    ]
