# Generated by Django 2.1.1 on 2018-10-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(max_length=35),
        ),
        migrations.AlterField(
            model_name='institute',
            name='email',
            field=models.EmailField(max_length=35),
        ),
    ]
