# Generated by Django 2.1.1 on 2018-10-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
