# Generated by Django 2.1.1 on 2018-10-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_management', '0003_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
